###################################
# Example Variables 📝
# ----------------------------------------------------
# Variables specific to the advanced-s3 example
###################################

variable "source_region" {
  type        = string
  description = "AWS region for the source S3 bucket and foundation module resources."
  default     = "us-east-1"
}

variable "replica_region" {
  type        = string
  description = "AWS region for the replica S3 bucket."
  default     = "eu-west-1"
}

variable "source_bucket_name" {
  type        = string
  description = "Name for the source S3 bucket created by the foundation module."
  # Default will be generated by the module if not provided, but setting one for clarity
  default = "foundation-adv-s3-source-example"
}

variable "replica_bucket_name" {
  type        = string
  description = "Name for the replica S3 bucket created directly in this example."
  default     = "foundation-adv-s3-replica-example"
}

variable "replication_role_name" {
  type        = string
  description = "Name for the IAM role created in this example for S3 replication."
  default     = "foundation-adv-s3-replication-role"
}

variable "is_replication_enabled" {
  type        = bool
  description = "Flag to enable S3 replication feature in the foundation module call."
  # Default to true for the primary fixture of this example
  default = true
}

variable "tags" {
  type        = map(string)
  description = "Tags to apply to resources created by the foundation module."
  default = {
    Environment = "example"
    Project     = "foundation-advanced-s3"
    ManagedBy   = "terraform"
  }
}

# Add other foundation module variables here if needed for specific testing,
# otherwise rely on module defaults or keep features disabled.
# For this example, we primarily need the S3 and replication inputs.

variable "is_enabled" {
  type        = bool
  description = "Master enable flag for the foundation module."
  default     = true
}

variable "is_s3_bucket_enabled" {
  type        = bool
  description = "Enable S3 bucket creation in the foundation module."
  default     = true # Required for replication
}

# Keep other features disabled by default for this focused example
variable "is_kms_key_enabled" {
  type        = bool
  description = "Enable KMS key creation (disabled for this example)."
  default     = false
}

variable "is_log_group_enabled" {
  type        = bool
  description = "Enable CloudWatch Log Group creation (disabled for this example)."
  default     = false
}

variable "is_oidc_provider_enabled" {
  type        = bool
  description = "Enable OIDC provider creation (disabled for this example)."
  default     = false
}

# Required inputs if KMS/Logs were enabled, providing defaults even though disabled
variable "kms_key_alias" {
  type        = string
  description = "Alias for KMS key (not used if is_kms_key_enabled=false)."
  default     = "alias/foundation-adv-s3-kms"
}

variable "log_group_name" {
  type        = string
  description = "Name for CloudWatch Log Group (not used if is_log_group_enabled=false)."
  default     = "/aws/codeartifact/foundation-adv-s3-logs"
}

variable "codeartifact_domain_name" {
  type        = string
  description = "Domain name used for resource naming consistency."
  default     = "foundation-adv-s3-domain"
}
