---
formatter: markdown table

sections:
  hide: []
  show:
    - inputs
    - outputs
    # Show modules called by this example
    - modules
    # Do not show resources directly created by the example itself (usually just the domain)
    # - resources

content: |-
  # Example: AWS CodeArtifact Repository with External Connections

  ## Overview
  > **Note:** This example demonstrates creating a repository with external connections (e.g., to public npmjs, pypi) using the `repository` module found in `modules/repository`.

  ### 🔑 Key Features Demonstrated
  - Creating a CodeArtifact domain within the example.
  - Calling the `repository` module and passing a single connection string via the `external_connection` input variable.
  - Using fixtures (`fixtures/*.tfvars`) and the `Makefile` to test the connection configuration (`default`) vs. disabling the module (`disabled`).

  ### 📋 Usage Guidelines
  1. **Initialize**: Run `make init` or `terraform init`.
  2. **Plan**: Run `make plan-default` or `terraform plan -var-file=fixtures/default.tfvars`. Review the plan to ensure external connections are included.
  3. **Apply**: Run `make apply-default` or `terraform apply -var-file=fixtures/default.tfvars`.
  4. **Verify**: Check the repository configuration in the AWS console or via AWS CLI to confirm external connections.
  5. **Cleanup**: Run `make destroy-default`.

  {{ .Header }}

  ## Example Inputs

  {{ .Inputs }}

  ## Example Outputs

  {{ .Outputs }}

  ## Modules Called

  {{ .Modules }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  anchor: true
  color: true
  description: true
  escape: true
  header: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true
