---
formatter: markdown table

header-from: main.tf
footer-from: ""

sections:
  show:
    - header
    - requirements
    - providers
    - modules
    - resources
    - inputs
    - outputs

content: |-
  # AWS CodeArtifact Foundation Module

  This Terraform module provisions the foundational resources required for AWS CodeArtifact operations. It sets up the necessary infrastructure components for secure artifact management, including encryption, logging, and backup capabilities.

  ## Overview

  The module creates and manages the following AWS resources:

  1. **KMS Key and Alias**
     - Dedicated KMS key for encrypting CodeArtifact artifacts and S3 bucket objects
     - Custom alias for easy key identification and management
     - Configurable deletion window for key protection

  2. **CloudWatch Log Group**
     - Centralized logging for CodeArtifact audit events
     - Configurable log retention period
     - Optional KMS encryption for log data

  3. **S3 Bucket**
     - Secure storage for CodeArtifact backups and migration artifacts
     - Versioning enabled for data protection
     - Server-side encryption using KMS or AES256
     - Public access blocked by default

  ## Features

  - **Modular Design**: Each component can be enabled/disabled independently using feature flags (`is_kms_key_enabled`, `is_log_group_enabled`, `is_s3_bucket_enabled`)
  - **Secure by Default**: Implements AWS security best practices
  - **Flexible Configuration**: Customizable through variables
  - **Comprehensive Logging**: Audit trail for all CodeArtifact operations
  - **Data Protection**: Encryption at rest for all sensitive data

  ## Usage

  ```hcl
  module "codeartifact_foundation" {
    source = "../../modules/foundation"

    # Feature Flags
    is_enabled = true

    # KMS Configuration
    kms_key_deletion_window = 7
    kms_key_alias          = "alias/codeartifact-encryption"

    # CloudWatch Logs Configuration
    log_group_name           = "/aws/codeartifact/audit-logs"
    log_group_retention_days = 30

    # S3 Configuration
    s3_bucket_name       = "my-company-codeartifact-backup"
    force_destroy_bucket = false

    # Resource Tags
    tags = {
      Environment = "production"
      Project     = "codeartifact"
      ManagedBy   = "terraform"
    }
  }
  ```

  ## Security Features

  1. **Encryption**
     - KMS encryption for artifacts and backups
     - Optional encryption for CloudWatch logs
     - Server-side encryption for S3 objects

  2. **Access Control**
     - S3 bucket public access blocked
     - KMS key policy with least privilege
     - CloudWatch logs encryption

  3. **Data Protection**
     - S3 bucket versioning
     - Configurable log retention
     - Protected KMS key deletion

  ## Best Practices

  1. **Resource Naming**
     - Use descriptive names for resources
     - Follow organizational naming conventions
     - Include environment or purpose in names

  2. **Security**
     - Enable KMS encryption for sensitive data
     - Set appropriate log retention periods
     - Block public access to S3 buckets

  3. **Cost Management**
     - Monitor CloudWatch log retention
     - Clean up unused backups
     - Use appropriate KMS key policies

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: replace

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
